<FloatLayout>:
    
    #dimensionamento percentual
    
    Button:
        size_hint_x: .8
        size_hint_y: .2
        #ou 
        size_hint: (.8, .2)
    
    #dimensionamento posicional
    
    Button:
        size_hint_x: None
        size_hint_y: None
        width: 4
        heigth: 2
        # ou 
        size: (4, 2)
    
    Button:
        size_hint:(None, None)
        size:(4,2)



 